/* generated by fix.bat */ 

/* modified by orz */

#if defined _MSC_VER
#		define ALLEGRO_MSVC 
#elif defined DJGPP
#		define ALLEGRO_DJGPP
#elif defined MINGW
#		define ALLEGRO_MINGW32
#elif defined BEOS
#		define ALLEGRO_BEOS
#elif defined (unix) || defined (__unix__) || defined (UNIX)
#		define ALLEGRO_UNIX
#elif defined MPW
#		define ALLEGRO_MPW
#else
#		error Allegro is misconfigured
#endif
