/* generated by fix.bat */ 
//modified by orz
#if 0
#elif defined _MSC_VER
#	define ALLEGRO_MSVC 
#elif defined DJGPP
#	define ALLEGRO_DJGPP
#elif defined __MINGW32__
#	define ALLEGRO_MINGW32
#elif defined __GCC__
#	define ALLEGRO_GCC
#else
#	error unrecognized platform
#endif

